# -*- coding: utf-8 -*-
"""firstclasspython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oIU2MrPCC6BH2NHkf7OonnQdiq82b6GV
"""

print(2-3)

print((100*1.1)*7)



print(100*1.1**7)



items = 10
price = 2
returned = 3
sent = "My remaining items are"
net_items = items-returned
print(sent, net_items)

type(sent)

#first name
first_sent = "Hassan"
#second name
second_sent = "Haider"
age= 30

print(f"The mans first name is",first_sent)

weight = 102
height =10
BMI = weight/height
BMI

